import {validateSubmission,checkedReview,validateFiles,mergeBoxes,uniqueFiles,cloudReady,statusText} from './core.js';
const $=id=>document.getElementById(id), SVG='http://www.w3.org/2000/svg';
let config,db,session,member,data={assets:[],trace:{},annotations:{state:{}}},selected={x:null,y:null,building_id:''},selectedPhoto,items=[],urls=[];
const local=()=>config.mode==='local';
function say(text,error=false){$('notice').textContent=text;$('notice').classList.toggle('error',error)}
function el(tag,text,cls){const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e}
function svg(tag,attrs){const e=document.createElementNS(SVG,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e}
async function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('timber-community-v1',1);r.onupgradeneeded=()=>{r.result.createObjectStore('submissions',{keyPath:'id'});r.result.createObjectStore('drafts')};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function storePut(store,value,key){return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite');const req=key===undefined?tx.objectStore(store).put(value):tx.objectStore(store).put(value,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);req.onerror=()=>reject(req.error)})}
async function storeGet(store,key){return new Promise((resolve,reject)=>{const req=db.transaction(store).objectStore(store).get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function allLocal(){return new Promise((resolve,reject)=>{const r=db.transaction('submissions').objectStore('submissions').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function request(path,{method='GET',body,headers={}}={}){
 if(!path.startsWith('/auth/')&&session?.expires_at<Date.now()/1000+60)await refreshSession();
 const response=await fetch(config.supabaseUrl+path,{method,headers:{apikey:config.supabasePublishableKey,...(session?.access_token?{Authorization:`Bearer ${session.access_token}`} :{}),...(body&&!(body instanceof Blob)?{'Content-Type':'application/json'}:{}),...headers},body:body instanceof Blob?body:body?JSON.stringify(body):undefined});
 const text=await response.text();let value;try{value=JSON.parse(text)}catch{value=text}
 if(!response.ok)throw Error(value?.message||value?.error_description||value?.msg||'服务暂时不可用，请保留草稿后重试。');return value;
}
function drawMap(){const root=$('atlas');root.replaceChildren();root.append(svg('rect',{width:1058,height:1186,fill:'#dfe5d4'}));
 if(!data.trace.roofSegments){const t=svg('text',{x:80,y:100,fill:'#395544','font-size':30});t.textContent='输入群口令后查看地图';root.append(t);return}
 if(data.satellite){root.append(svg('image',{href:data.satellite,width:1058,height:1186,opacity:.65}))}
 for(const b of mergeBoxes(data.trace,data.annotations.state)){const road=['N05','N06'].includes(b.id);const r=svg('rect',{x:b.x,y:b.y,width:b.w,height:b.h,fill:road?'#c8c0a4':b.kind==='redRoof'?'#bd7654':'#879889',stroke:'#344c3c','stroke-width':2,opacity:.86,role:'button',tabindex:0,'aria-label':`建筑 ${b.id}`,class:selected.building_id===b.id?'active':''});const choose=()=>{selected={building_id:b.id,x:Math.round(b.x+b.w/2),y:Math.round(b.y+b.h/2)};showLocation();drawMap()};r.onclick=e=>{e.stopPropagation();choose()};r.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose()}};root.append(r)}
 if(selected.x!=null)root.append(svg('circle',{cx:selected.x,cy:selected.y,r:12,fill:'#f3dc78',stroke:'#24483a','stroke-width':4}));
 root.onclick=e=>{const p=root.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const at=p.matrixTransform(root.getScreenCTM().inverse());selected={building_id:'',x:Math.round(at.x),y:Math.round(at.y)};showLocation();drawMap()};
 $('map-version').textContent='资料版本：'+(data.annotations.exportedAt||'待核准').slice(0,10);
}
function showLocation(){const id=selected.building_id;$('selected-title').textContent=id?`建筑 ${id}`:selected.x!=null?'已选地图位置':'地点还不确定';$('selected-note').textContent=data.annotations.state?.roofs?.[id]||'这个位置还可以继续补充照片和说明。';$('building').value=id;$('location-label').textContent=selected.x!=null?`位置：图上 ${selected.x}, ${selected.y}（底图像素，非经纬度）`:'位置：尚未指定';$('linked-photos').replaceChildren();for(const p of data.assets.filter(p=>data.annotations.state?.photos?.[p.id]?.roofId===id&&id)){const b=el('button',null,'quiet');const im=el('img');im.src=p.preview;im.alt=p.title;b.append(im);b.onclick=()=>showPhoto(p);$('linked-photos').append(b)}}
function showPhoto(p){selectedPhoto=p;$('large-photo').src=p.preview;$('photo-title').textContent=`${p.id} · ${p.title}`;$('photo-info').textContent=`${p.captureDate||'拍摄日期待确认'} · ${p.description||''} · ${data.annotations.state?.photos?.[p.id]?.x!=null?'已有指认':'位置待指认'}`;$('photo-dialog').showModal()}
function drawGallery(){const filter=$('era-filter').value;const list=data.assets.filter(p=>filter==='all'||filter==='new'&&p.batch==='new'||filter==='old'&&p.batch!=='new'||filter==='unplaced'&&data.annotations.state?.photos?.[p.id]?.x==null||p.captureDate?.startsWith(filter));$('photos').replaceChildren();$('gallery-summary').textContent=`共 ${data.assets.length} 份资料，当前显示 ${list.length} 份。照片年份与地点确认分别记录。`;
 for(const p of list){const b=el('button',null,'photo-card');b.setAttribute('aria-label',`${p.id} ${p.title}`);const im=el('img');im.src=p.preview;im.alt=p.title;im.loading='lazy';b.append(im,el('b',p.title),el('small',`${p.id} · ${p.captureDate||'年份待确认'}`),el('small',data.annotations.state?.photos?.[p.id]?.x!=null?'已定位':'等待指认'));b.onclick=()=>showPhoto(p);$('photos').append(b)}
}
async function loadCloud(){const maps=await request('/rest/v1/map_versions?select=*&order=created_at.desc&limit=1');if(maps.length){data={assets:[],trace:{},annotations:{state:{}},...maps[0].payload};for(const p of data.assets){if(p.object_path){const signed=await request('/storage/v1/object/sign/timber-private/'+p.object_path,{method:'POST',body:{expiresIn:3600}});p.preview=config.supabaseUrl+'/storage/v1'+signed.signedURL}else p.preview=''}}if(data.satellite_path){const v=await request('/storage/v1/object/sign/timber-private/'+data.satellite_path,{method:'POST',body:{expiresIn:3600}});data.satellite=config.supabaseUrl+'/storage/v1'+v.signedURL}drawMap();drawGallery();await refreshItems()}
async function refreshItems(){items=local()?await allLocal():await request('/rest/v1/submissions?select=*,assets(*)&order=created_at.desc');items.sort((a,b)=>b.created_at.localeCompare(a.created_at));drawItems()}
async function drawItems(){urls.forEach(u=>URL.revokeObjectURL(u));urls=[];$('submissions').replaceChildren();$('queue-hint').textContent=local()?'以下内容只保存在这台设备，还没有发给伙伴。':'内部共创资料。仅整理者可以确认是否采用。';for(const s of items){const c=el('article',null,'submission');c.append(el('strong',s.title),el('small',`${s.author} · ${statusText[s.status]} · ${s.privacy==='private'?'仅本人和整理者':'内部伙伴'} · ${s.captured_year||'年份待确认'}`),el('p',s.story||''));if(s.building_id)c.append(el('small','地点：'+s.building_id));if(s.review_note)c.append(el('p','核对说明：'+s.review_note));for(const f of s.files||s.assets||[]){const b=el('button',`查看附件：${f.name||f.filename}`,'quiet');b.onclick=async()=>{try{let u;if(f.blob){u=URL.createObjectURL(f.blob);urls.push(u)}else{const v=await request('/storage/v1/object/sign/timber-private/'+f.object_path,{method:'POST',body:{expiresIn:60}});u=config.supabaseUrl+'/storage/v1'+v.signedURL}const a=el('a','打开附件');a.href=u;a.target='_blank';a.rel='noopener';c.append(a);a.click()}catch(e){say(e.message,true)}};c.append(b)}
 if((local()||member?.role==='admin')&&['pending','needs_info'].includes(s.status)){const n=el('input');n.placeholder='核对说明（如：还缺哪一面照片）';n.setAttribute('aria-label',`${s.title} 的核对说明`);c.append(n);for(const [status,label] of [['approved','确认资料'],['needs_info','请补充']]){const b=el('button',label,'quiet');b.onclick=async()=>{try{b.disabled=true;if(local()){const current=await storeGet('submissions',s.id);await storePut('submissions',checkedReview(current,s.revision,status,n.value))}else await request('/rest/v1/rpc/review_submission',{method:'POST',body:{p_id:s.id,p_expected_revision:s.revision,p_status:status,p_review_note:n.value}});await refreshItems();say('核对结果已保存。正式地图不会被自动覆盖。')}catch(e){say(e.message,true)}finally{b.disabled=false}};c.append(b)}}$('submissions').append(c)}if(!items.length)$('submissions').append(el('p','还没有提交。可以先留下一段你记得的故事。','small'))}
function formValue(){return {author:$('author').value.trim(),title:$('title').value.trim(),story:$('story').value.trim(),captured_year:$('year').value.trim(),building_id:$('building').value.trim()||null,x:selected.x,y:selected.y,kind:$('kind').value,privacy:$('privacy').value}}
async function saveDraft(){try{await storePut('drafts',{...formValue(),selected},'current');$('draft-status').textContent='文字草稿已保存在本机。'}catch{$('draft-status').textContent='本机空间不足，请导出草稿。'}}
async function fileValues(){const fs=Array.from($('files').files);validateFiles(fs);const result=[];for(const f of fs){const digest=await crypto.subtle.digest('SHA-256',await f.arrayBuffer());result.push({name:f.name,mime:f.type||(/\.heic$/i.test(f.name)?'image/heic':/\.heif$/i.test(f.name)?'image/heif':'application/octet-stream'),bytes:f.size,sha256:[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join(''),blob:f})}return uniqueFiles(result)}
async function submit(e){e.preventDefault();const b=$('submit');b.disabled=true;try{const value=validateSubmission(formValue());let files=await fileValues();let draft=await storeGet('drafts','upload');if(draft){if(draft.scope!==(local()?'local':session?.user.id))throw Error('此设备有另一账号的未完成上传，请先用原账号完成。');value.id=draft.id;files=draft.files;say('正在重试上次未完成的附件上传。')}else{value.id=crypto.randomUUID();draft={...value,files,scope:local()?'local':session?.user.id};await storePut('drafts',draft,'upload')}
 if(local()){await storePut('submissions',{...draft,status:'pending',revision:1,created_at:new Date().toISOString()});say('已保存到本机待核对。尚未上传，也未通知任何伙伴。')}
 else{if(!member?.active)throw Error('账号尚未获准加入，请联系整理者。');const s={...draft};delete s.files;delete s.scope;const exists=await request('/rest/v1/submissions?id=eq.'+s.id+'&select=id');if(!exists.length)await request('/rest/v1/submissions',{method:'POST',body:s,headers:{Prefer:'return=representation'}});const existing=await request('/rest/v1/assets?submission_id=eq.'+s.id+'&select=sha256');for(const f of files){if(existing.some(a=>a.sha256===f.sha256))continue;const suffix=f.name.split('.').pop().toLowerCase();const path=`${session.user.id}/${s.id}/${f.sha256}.${suffix}`;try{await request('/storage/v1/object/timber-private/'+path,{method:'POST',body:f.blob,headers:{'Content-Type':f.mime,'x-upsert':'false'}})}catch(err){if(!/already exists|Duplicate/i.test(err.message))throw err}await request('/rest/v1/rpc/register_asset',{method:'POST',body:{p_submission_id:s.id,p_object_path:path,p_filename:f.name,p_mime:f.mime,p_bytes:f.bytes,p_sha256:f.sha256}})}say('已提交到内部资料库，等待核对。')}
 await storePut('drafts',null,'upload');await storePut('drafts',null,'current');$('contribution-form').reset();selected={x:null,y:null,building_id:''};showLocation();drawMap();$('draft-status').textContent='提交已保存。';await refreshItems();
 }catch(err){say(err.message+' 草稿仍保留在本机。',true)}finally{b.disabled=false}}
function download(name,value){const a=el('a');const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function init(){config=await fetch('./config.json').then(r=>r.json());if(config.mode==='local'&&!['localhost','127.0.0.1'].includes(location.hostname))throw Error('本机资料模式不能在公开网址使用。');db=await openDB();$('contribution-form').onsubmit=submit;$('contribution-form').addEventListener('input',saveDraft);$('files').onchange=async()=>{try{const v=await fileValues();$('file-note').textContent=`已选 ${v.length} 个不重复文件。点击保存后，未完成上传的附件会保留在本机。`}catch(e){say(e.message,true)}};
 $('era-filter').onchange=drawGallery;$('use-location').onclick=()=>{showLocation();location.hash='contribute'};$('clear-location').onclick=()=>{selected={x:null,y:null,building_id:''};showLocation();drawMap()};$('close-photo').onclick=()=>$('photo-dialog').close();$('identify-photo').onclick=()=>{const p=selectedPhoto;$('photo-dialog').close();$('kind').value='correction';$('title').value=`指认照片 ${p.id}`;$('story').value=`照片：${p.id}，${p.title}\n我记得这里是：`;$('files').value='';const at=data.annotations.state?.photos?.[p.id];selected=at?.x!=null?{x:at.x,y:at.y,building_id:at.roofId||''}:{x:null,y:null,building_id:''};showLocation();drawMap();saveDraft();location.hash='map'};
 $('export-draft').onclick=()=>download('木材厂-文字草稿.json',{schema:'timber-contribution-v1',...formValue()});$('export-submissions').onclick=async()=>{if(!local())return;say('正在整理附件，文件较大时需要稍等。');const out=await allLocal();for(const s of out)for(const f of s.files||[]){f.base64=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f.blob)});delete f.blob}download('木材厂-本机共创提交.json',{schema:'timber-contributions-v1',submissions:out});say('导出已准备好，包含这台设备保存的提交和附件。')};
 const d=await storeGet('drafts','current');if(d){for(const [key,id] of [['author','author'],['title','title'],['story','story'],['captured_year','year'],['building_id','building'],['kind','kind'],['privacy','privacy']])if(d[key])$(id).value=d[key];selected=d.selected||selected;showLocation();$('draft-status').textContent='已恢复上次文字草稿。未提交的新附件请重新选择。'}
 if(local()){data=await fetch('./private-data/catalog.json').then(r=>r.json());$('connection').textContent='本机资料 · 尚未联网';$('legacy-link').hidden=false;const hero=data.assets.find(p=>p.id==='N20260926-05');if(hero){const im=el('img');im.src=hero.preview;im.alt='2020 年航拍中的红砖住宅与道路';$('hero-figure').replaceChildren(im,el('figcaption',`${hero.captureDate} · 航拍资料，作为建筑位置参照`))}say('已接入这次的新素材和已有地图标注。这里的保存只在本机，伙伴入口等待云服务开通。');drawMap();showLocation();drawGallery();await refreshItems();await loadModel()}
 else{$('login-section').hidden=false;$('submit').textContent='提交给共创伙伴';$('submit').disabled=true;$('export-submissions').hidden=true;$('connection').textContent=cloudReady(config)?'内部共创 · 凭群口令加入':'伙伴入口尚未开通';say(cloudReady(config)?'输入名字和群口令后，就能查看地图、照片并补充记忆。':'网页已准备好，云端账号与私有存储尚未配置。当前不能接收伙伴提交。');$('login-form').hidden=!cloudReady(config);drawMap();drawGallery()}
 $('login-form').onsubmit=async e=>{e.preventDefault();$('join').disabled=true;try{await ensureSession();const result=await request('/rest/v1/rpc/redeem_invite',{method:'POST',body:{p_code:$('invite-code').value.trim(),p_display_name:$('nickname').value.trim()}});if(!result.success)throw Error(result.reason==='rate_limited'?'口令输错次数较多，请 15 分钟后再试。':result.reason==='contact_admin'?'此身份已停用，请联系整理者。':'口令无效、已过期或已用完，请向群里的整理者索取新口令。');$('invite-code').value='';await enterCommunity()}catch(e){say(e.message,true)}finally{$('join').disabled=false}};
 $('owner-session').onclick=async()=>{try{await ensureSession();$('owner-uid').textContent='本机身份：'+session.user.id;await enterCommunity()}catch(e){say('身份已准备。整理者配置成员权限后，再点一次进入。'+e.message,true)}};
 $('create-invite').onclick=async()=>{try{$('create-invite').disabled=true;const code=await request('/rest/v1/rpc/create_invite',{method:'POST',body:{p_label:'微信群伙伴 '+new Date().toLocaleDateString(),p_days:7,p_max_uses:20}});$('invite-result-label').hidden=false;$('invite-result').value=code;await drawInvites();say('口令已生成，可复制到共创群。')}catch(e){say(e.message,true)}finally{$('create-invite').disabled=false}};
 $('logout').onclick=async()=>{try{await request('/auth/v1/logout',{method:'POST'})}finally{await storePut('drafts',null,'auth-session');session=null;member=null;location.reload()}};
 if(!local()&&cloudReady(config)){try{session=await storeGet('drafts','auth-session');if(session){await refreshSession();await enterCommunity()}}catch{say('需要重新输入群口令。未完成的草稿仍保存在本机。',true)}}

}
async function loadModel(){try{const check=await fetch('./private-data/model/home-pilot.glb',{method:'HEAD'});if(!check.ok)return;const script=el('script');script.type='module';script.src='./vendor/model-viewer.min.js';document.head.append(script);const viewer=el('model-viewer');viewer.setAttribute('src','./private-data/model/home-pilot.glb');viewer.setAttribute('camera-controls','');viewer.setAttribute('shadow-intensity','.7');viewer.setAttribute('alt','一排红砖住宅的结构样板，尺寸待测量');viewer.setAttribute('touch-action','pan-y');$('model-slot').replaceChildren(viewer,el('p','可拖动旋转、双指缩放。当前是待核准的结构样板，尚未完成真实尺寸与地形验收。','small'));const a=el('a','下载可编辑 Blender 样板 ↗');a.href='./private-data/model/home-pilot.blend';$('model-slot').append(a);$('model-evidence').textContent='建模依据：既有住宅照片及你的住户标注。估计尺寸、未知背面与高差保留待确认，不作为实测模型。'}catch{}}
init().catch(e=>say('资料加载暂未完成：'+e.message,true));

async function persistSession(value){session={...value,expires_at:value.expires_at||Math.floor(Date.now()/1000)+(value.expires_in||3600)};await storePut('drafts',session,'auth-session')}
async function refreshSession(){if(!session?.refresh_token)return;if(session.expires_at>Date.now()/1000+60)return;await persistSession(await request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:session.refresh_token}}))}
async function ensureSession(){if(!session)session=await storeGet('drafts','auth-session');if(session){await refreshSession();return}await persistSession(await request('/auth/v1/signup',{method:'POST',body:{data:{source:'timber-community'}}}))}
async function enterCommunity(){const rows=await request('/rest/v1/members?user_id=eq.'+session.user.id+'&select=*');member=rows[0];if(!member?.active)throw Error('还未加入内部共创名单。');$('login-section').hidden=true;$('logout').hidden=false;$('submit').disabled=false;$('author').value=member.display_name;$('connection').textContent='内部共创 · '+member.display_name;$('invite-admin').hidden=member.role!=='admin';await loadCloud();if(member.role==='admin'){await drawInvites();addLocalImport();}say('进来了。先在地图上认认地方，也可以直接传照片。')}
async function drawInvites(){const list=await request('/rest/v1/invite_codes?select=id,label,expires_at,use_limit,use_count,revoked_at&order=created_at.desc');$('invite-list').replaceChildren();for(const i of list){const row=el('p',`${i.label} · 已用 ${i.use_count}/${i.use_limit} · ${i.revoked_at?'已停用':'到期 '+new Date(i.expires_at).toLocaleDateString()}`);if(!i.revoked_at){const b=el('button','停用这条口令','quiet');b.onclick=async()=>{try{await request('/rest/v1/rpc/revoke_invite',{method:'POST',body:{p_invite_id:i.id}});await drawInvites()}catch(e){say(e.message,true)}};row.append(b)}$('invite-list').append(row)}}

function addLocalImport(){if(!['localhost','127.0.0.1'].includes(location.hostname)||$('import-local'))return;const b=el('button','导入本机已整理资料到内部库','quiet');b.id='import-local';b.onclick=async()=>{b.disabled=true;try{await importLocalCatalog();await loadCloud();say('现有地图标注和资料预览已存入内部库。原始大文件仍保留在本机。')}catch(e){say('导入暂未完成：'+e.message+'。可以重试，已上传的预览会复用。',true)}finally{b.disabled=false}};$('invite-admin').append(b)}
async function importLocalCatalog(){const source=new URL('../timber-community/',location.href);const resp=await fetch(new URL('private-data/catalog.json',source));if(!resp.ok)throw Error('没有找到本机资料包');const catalog=await resp.json();const heads=await request('/rest/v1/map_versions?select=id,payload&order=created_at.desc&limit=1');if(heads[0]?.payload?.importBatch==='timber-20260926')return;
 const existing=await request('/rest/v1/submissions?owner_id=eq.'+session.user.id+'&title=eq.'+encodeURIComponent('资料归档 · 2026-09-26')+'&select=id');let id=existing[0]?.id;if(!id){id=crypto.randomUUID();await request('/rest/v1/submissions',{method:'POST',body:{id,author:member.display_name,title:'资料归档 · 2026-09-26',story:'已有照片预览与已保存的地图标注。照片中的年代与位置以各条资料为准，未确认之处继续保留。',kind:'photo',privacy:'team'}})}
 const known=await request('/rest/v1/assets?submission_id=eq.'+id+'&select=*');
 async function uploadPreview(url,name,mime){const r=await fetch(new URL(url,source));if(!r.ok)throw Error(name+' 未能读取');const blob=await r.blob();const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()))].map(x=>x.toString(16).padStart(2,'0')).join('');const prior=known.find(f=>f.sha256===hash);if(prior)return prior.object_path;const path=session.user.id+'/'+id+'/'+hash+'.'+name.split('.').pop();try{await request('/storage/v1/object/timber-private/'+path,{method:'POST',body:blob,headers:{'Content-Type':mime||blob.type,'x-upsert':'false'}})}catch(e){if(!/already exists|Duplicate/i.test(e.message))throw e}await request('/rest/v1/rpc/register_asset',{method:'POST',body:{p_submission_id:id,p_object_path:path,p_filename:name,p_mime:mime||blob.type,p_bytes:blob.size,p_sha256:hash}});known.push({sha256:hash,object_path:path});return path}
 for(let i=0;i<catalog.assets.length;i++){const a=catalog.assets[i];say('正在归档资料预览 '+(i+1)+'/'+catalog.assets.length);a.object_path=await uploadPreview(a.preview,a.id+'.jpg','image/jpeg');delete a.preview}
 if(catalog.satellite){catalog.satellite_path=await uploadPreview(catalog.satellite,'satellite.png','image/png');delete catalog.satellite}
 catalog.importBatch='timber-20260926';await request('/rest/v1/rpc/create_map_version',{method:'POST',body:{p_payload:catalog,p_note:'接入现有地图标注、16份新增素材及之前的资料预览；未确认的位置继续保留。',p_previous_id:heads[0]?.id||null}})
}
